### ISSUE TITLE
Use inotify (fswatch for mac?) + checksum in the watcher code instead of polling the modified date

### ISSUE THREAD

**Issue by nootanghimire** [dafuq-is/backend#16]
Currently the watcher code, we have a infinite loop that constantly checks filetime and rebuild if it detects change. 

It's probably better to use the combination of inotify (and similar tools for mac/windows) and file checksums.

**Comment by Avasz** [comment]
Basic requirements has been fixed in the `init` branch.  

But few problems still exist.  
1. The init script I made runs the backend with a custom command, and gives the name `dafuqis-backend` to the process. And it kills/restarts - mainly kills - only the process run by that script named `dafuqis-backend`.   
Problem: If someone started the script with `python3 index.py` init won't be able to kill it, and maybe port conflict will arise if s/he uses ./init.sh simultaneously to run the backend.   
We might be able to fix this by updating `README` file with `./init.sh` instead of `python3 index.py`. And maybe check if `index.py` is run directly.  


2. The `legacy_watch` method runs a loop with 1 second delay, sometimes the app might not restart because of it not detecting change in checksum... (happened to me twice).
